#ifndef BTSTACK_CONFIG_H
#define BTSTACK_CONFIG_H
#define HAVE_AES128
#define HAVE_BTSTACK_STDIN
#define HAVE_LWIP
#define HAVE_MALLOC
#define MBEDTLS_ECC_P256

#define ENABLE_BLE
#define ENABLE_CLASSIC
#define ENABLE_LE_CENTRAL
#define ENABLE_LE_PERIPHERAL
#define ENABLE_LOG_INFO
#define ENABLE_PRINTF_HEXDUMP

#endif /* BTSTACK_CONFIG_H */